// <auto-generated/>
using Microsoft.AspNetCore.Components;
using System.Text;

namespace BrowserTools.Pages
{
    public partial class CountdownNumbers
    {
        private int[] ValidNumbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 25, 50, 75, 100];
        private int[] SmallNumbers = [1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10];
        private int[] BigNumbers = [25, 50, 75, 100];
        private int Total = 0;
        private int[] Numbers = [0, 0, 0, 0, 0, 0];

        private bool Running = false;

        private string InfoMessage = "";

        private Dictionary<int, List<string>> Solutions = [];

        private MarkupString Output = new MarkupString();

        private MarkupString Options = new MarkupString("<option value=1>1</option><option value=2>2</option><option value=3>3</option><option value=4>4</option><option value=5>5</option><option value=6>6</option><option value=7>7</option><option value=8>8</option><option value=9>9</option><option value=10>10</option><option value=25>25</option><option value=50>50</option><option value=75>75</option><option value=100>100</option>");


        private void Random()
        {
            Random random = new();

            Numbers = SmallNumbers.Concat(BigNumbers).OrderBy(_ => random.Next()).Take(6).ToArray();
            Total = random.Next(100, 999);
        }

        private void Random6()
        {
            Random random = new();

            Numbers = SmallNumbers.OrderBy(_ => random.Next()).Take(6).ToArray();
            Total = random.Next(100, 999);
        }

        private void Random51()
        {
            Random random = new();

            Numbers = SmallNumbers.OrderBy(_ => random.Next()).Take(5).Concat(BigNumbers.OrderBy(_ => random.Next()).Take(1)).ToArray();
            Total = random.Next(100, 999);
        }

        private void Random42()
        {
            Random random = new();

            Numbers = SmallNumbers.OrderBy(_ => random.Next()).Take(4).Concat(BigNumbers.OrderBy(_ => random.Next()).Take(2)).ToArray();
            Total = random.Next(100, 999);
        }

        private void Random33()
        {
            Random random = new();

            Numbers = SmallNumbers.OrderBy(_ => random.Next()).Take(3).Concat(BigNumbers.OrderBy(_ => random.Next()).Take(3)).ToArray();
            Total = random.Next(100, 999);
        }

        private void Random24()
        {
            Random random = new();

            Numbers = SmallNumbers.OrderBy(_ => random.Next()).Take(2).Concat(BigNumbers.OrderBy(_ => random.Next()).Take(4)).ToArray();
            Total = random.Next(100, 999);
        }

        private async Task Solve()
        {
            Running = true;
            InfoMessage = "";
            Solutions.Clear();

            if (Total < 100 || Total > 999)
            {
                InfoMessage = "Invalid total, expecting between 100 and 999";
                Running = false;
                return;
            }

            if (Numbers.Except(ValidNumbers).Any())
            {
                InfoMessage = "Invalid number, expecting only 1-10, 25, 50, 75 and 100";
                Running = false;
                return;
            }

            if (Numbers.Where(x => x <= 10).GroupBy(x => x).Where(x => x.Count() > 2).Any())
            {
                InfoMessage = "Invalid numbers, expecting a maximum of 2 numbers between 1 and 10";
                Running = false;
                return;
            }

            if (Numbers.Where(x => x > 10).GroupBy(x => x).Where(x => x.Count() > 1).Any())
            {
                InfoMessage = "Invalid numbers, expecting a maximum of 1 number out of 25, 50, 75 and 100";
                Running = false;
                return;
            }

            if (Numbers.Aggregate(1, (total, x) => total * x) < Total)
            {
                InfoMessage = "No solution possible, product of numbers is less than total";
                Running = false;
                return;
            }

            await Task.Yield();

            long TickStart = DateTime.UtcNow.Ticks;

            CancellationTokenSource tokenTimeout = new CancellationTokenSource(TimeSpan.FromSeconds(30));
            CancellationToken token = tokenTimeout.Token;

            Solutions = await GetEquation(Total, Numbers, token);

            long TickEnd = DateTime.UtcNow.Ticks;

            if (Solutions.ContainsKey(Total))
            {
                Output = new MarkupString(string.Join("", Solutions[Total]));
                InfoMessage = $"Solved in {new TimeSpan(TickEnd - TickStart).TotalSeconds}s, found {Solutions[Total].Count()} solution{(Solutions[Total].Count() == 1 ? "" : "s")}.";
            }
            else if (Solutions.Where(x => x.Key != Total).Any())
            {
                int i = 1;

                while (i <= 11)
                {
                    if (Solutions.ContainsKey(Total + i))
                    {
                        Output = new MarkupString(string.Join("", Solutions[Total + i]));
                        InfoMessage = $"Closest solution is {Total + i}, took {new TimeSpan(TickEnd - TickStart).TotalSeconds}s, found {Solutions[Total + i].Count()} solution{(Solutions[Total + i].Count() == 1 ? "" : "s")}.";
                        break;
                    }
                    else if (Solutions.ContainsKey(Total - i))
                    {
                        Output = new MarkupString(string.Join("", Solutions[Total - i]));
                        InfoMessage = $"Closest solution is {Total - i}, took  {new TimeSpan(TickEnd - TickStart).TotalSeconds}s, found {Solutions[Total - i].Count()} solution{(Solutions[Total - i].Count() == 1 ? "" : "s")}.";
                        break;
                    }
                    i++;
                }

                if (i == 11)
                {
                    if (string.IsNullOrWhiteSpace(InfoMessage))
                    {
                        InfoMessage = $"No solution found, tool {new TimeSpan(TickEnd - TickStart).TotalSeconds}s";
                    }
                }
            }
            else
            {
                if (string.IsNullOrWhiteSpace(InfoMessage))
                {
                    InfoMessage = $"No solution found, tool {new TimeSpan(TickEnd - TickStart).TotalSeconds}s";
                }
            }

            Running = false;
        }

        async Task<Dictionary<int, List<string>>> GetEquation(int target, int[] numbers, CancellationToken token)
        {
            try
            {
                Dictionary<int, List<string>> ret = [];

                IEnumerable<int[]> numberCombinations = GetUniqueCombinations(numbers, 6);
                IEnumerable<string> operationCombinations = GetOperations();

                foreach (int[] numberItem in numberCombinations)
                {
                    token.ThrowIfCancellationRequested();

                    foreach (string operationsItem in operationCombinations)
                    {
                        token.ThrowIfCancellationRequested();

                        if (operationsItem.Count() + 1 == numberItem.Count())
                        {
                            bool skip = false;
                            int res = numberItem[0];

                            if (res == 1 && (operationsItem[0] == '*' || operationsItem[0] == '/'))
                                skip = true;

                            for (int j = 0; j < operationsItem.Count(); j++)
                            {
                                if (res <= 0)
                                    skip = true;

                                if (j > 0 && res == 1 && (operationsItem[0] == '*' || operationsItem[0] == '/'))
                                    skip = true;

                                if (operationsItem[j] == '+')
                                {
                                    res += numberItem[j + 1];
                                }
                                else if (operationsItem[j] == '-')
                                {
                                    res -= numberItem[j + 1];
                                }
                                else if (operationsItem[j] == '*')
                                {
                                    if (numberItem[j + 1] == 1)
                                        skip = true;

                                    res *= numberItem[j + 1];
                                }
                                else if (operationsItem[j] == '/')
                                {
                                    if (numberItem[j + 1] == 1)
                                        skip = true;

                                    if (res % numberItem[j + 1] != 0)
                                        skip = true;

                                    res /= numberItem[j + 1];
                                }
                            }

                            if (!skip && (res == target || (res + 10 >= target && res - 10 <= target)))
                            {
                                StringBuilder result = new StringBuilder();

                                result.Append("<span>");

                                if (res != target)
                                {
                                    result.Append($"{res} = ");
                                }

                                for (int j = 0; j < numberItem.Count() - 1; j++)
                                {
                                    result.Append("(");
                                }

                                result.Append($"{numberItem.First()} ");

                                for (int j = 1; j < numberItem.Count(); j++)
                                {
                                    result.Append($"{operationsItem[j - 1]} {numberItem.Skip(j).First()}) ");
                                }

                                result.Append("</span> <br />");

                                if (!ret.ContainsKey(res))
                                    ret.Add(res, new List<string>());

                                ret[res].Add(result.ToString());
                            }
                        }

                        await Task.Yield();
                    }
                }

                return ret;
            }
            catch
            {
                InfoMessage = "Operation timed out";
                return [];
            }
        }

        private static IEnumerable<string> GetOperations()
        {
            HashSet<string> ret = [];

            for (int i = 0; i < 4; i++)
            {
                for (int j = 0; j < 4; j++)
                {
                    for (int k = 0; k < 4; k++)
                    {
                        for (int l = 0; l < 4; l++)
                        {
                            for (int m = 0; m < 4; m++)
                            {
                                char[] item = [' ', ' ', ' ', ' ', ' '];

                                item[0] = i == 0 ? '+' : i == 1 ? '-' : i == 2 ? '*' : i == 3 ? '/' : ' ';
                                item[1] = j == 0 ? '+' : j == 1 ? '-' : j == 2 ? '*' : j == 3 ? '/' : ' ';
                                item[2] = k == 0 ? '+' : k == 1 ? '-' : k == 2 ? '*' : k == 3 ? '/' : ' ';
                                item[3] = l == 0 ? '+' : l == 1 ? '-' : l == 2 ? '*' : l == 3 ? '/' : ' ';
                                item[4] = m == 0 ? '+' : m == 1 ? '-' : m == 2 ? '*' : m == 3 ? '/' : ' ';

                                string stringCheck1 = string.Join("", item[0..1]);
                                string stringCheck2 = string.Join("", item[0..2]);
                                string stringCheck3 = string.Join("", item[0..3]);
                                string stringCheck4 = string.Join("", item[0..4]);
                                string stringCheck5 = string.Join("", item[0..5]);

                                if (!ret.Any(x => x.Equals(stringCheck1)))
                                {
                                    ret.Add(stringCheck1);
                                }

                                if (!ret.Any(x => x.Equals(stringCheck2)))
                                {
                                    ret.Add(stringCheck2);
                                }

                                if (!ret.Any(x => x.Equals(stringCheck3)))
                                {
                                    ret.Add(stringCheck3);
                                }

                                if (!ret.Any(x => x.Equals(stringCheck4)))
                                {
                                    ret.Add(stringCheck4);
                                }

                                if (!ret.Any(x => x.Equals(stringCheck5)))
                                {
                                    ret.Add(stringCheck5);
                                }

                            }
                        }
                    }
                }
            }

            return ret;
        }

        private static IEnumerable<int[]> GetUniqueCombinations(IEnumerable<int> items, int count)
        {
            List<int[]> ret = [];
            HashSet<string> check = [];

            foreach (IEnumerable<int> item in GetCombinations(items, count))
            {
                string stringCheck2 = string.Join("|", item.Take(2));
                string stringCheck3 = string.Join("|", item.Take(3));
                string stringCheck4 = string.Join("|", item.Take(4));
                string stringCheck5 = string.Join("|", item.Take(5));
                string stringCheck6 = string.Join("|", item.Take(6));

                if (!check.Any(x => x.Equals(stringCheck2)))
                {
                    check.Add(stringCheck2);
                    ret.Add(item.Take(2).ToArray());
                }

                if (!check.Any(x => x.Equals(stringCheck3)))
                {
                    check.Add(stringCheck3);
                    ret.Add(item.Take(3).ToArray());
                }

                if (!check.Any(x => x.Equals(stringCheck4)))
                {
                    check.Add(stringCheck4);
                    ret.Add(item.Take(4).ToArray());
                }

                if (!check.Any(x => x.Equals(stringCheck5)))
                {
                    check.Add(stringCheck5);
                    ret.Add(item.Take(5).ToArray());
                }

                if (!check.Any(x => x.Equals(stringCheck6)))
                {
                    check.Add(stringCheck6);
                    ret.Add(item.Take(6).ToArray());
                }
            }

            return ret;
        }

        private static IEnumerable<IEnumerable<T>> GetCombinations<T>(IEnumerable<T> items, int count)
        {
            int i = 0;

            foreach (T? item in items)
            {
                if (count > 0)
                {
                    if (count == 1)
                    {
                        yield return new T[] { item };
                    }
                    else
                    {
                        foreach (IEnumerable<T> result in GetCombinations(items.Take(i).Concat(items.Skip(i + 1)), count - 1))
                        {
                            yield return new T[] { item }.Concat(result);
                        }
                    }

                    ++i;
                }
            }
        }
    }
}