// <auto-generated/>
using Microsoft.AspNetCore.Components;
using System.Data;
using System.Net.ServerSentEvents;
using System.Text;
using System.Text.RegularExpressions;

namespace BrowserTools.Pages
{
    public partial class CountdownNumbers
    {
        private int[] ValidNumbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 25, 50, 75, 100];
        private int[] ValidScaryNumbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 37, 62, 87];
        private int[] SmallNumbers = [1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10];
        private int[] BigNumbers = [25, 50, 75, 100];
        private int[] BigScaryNumbers = [12, 37, 62, 87];
        private int Total = 0;
        private int[] Numbers = [0, 0, 0, 0, 0, 0];

        private bool IsScary = false;

        private bool Running = false;

        private string InfoMessage = "";

        private Dictionary<int, HashSet<MarkupString>> Solutions = [];

        private int ActiveTab;

        protected override void OnInitialized()
        {
            ActiveTab = Solutions.Keys.FirstOrDefault();
        }

        private MarkupString Output = new MarkupString();

        private MarkupString Options = new MarkupString("<option value=1>1</option><option value=2>2</option><option value=3>3</option><option value=4>4</option><option value=5>5</option><option value=6>6</option><option value=7>7</option><option value=8>8</option><option value=9>9</option><option value=10>10</option><option value=25>25</option><option value=50>50</option><option value=75>75</option><option value=100>100</option>");

        private MarkupString OptionsScary = new MarkupString("<option value=1>1</option><option value=2>2</option><option value=3>3</option><option value=4>4</option><option value=5>5</option><option value=6>6</option><option value=7>7</option><option value=8>8</option><option value=9>9</option><option value=10>10</option><option value=12>12</option><option value=37>37</option><option value=62>62</option><option value=87>87</option>");

        private void Reset()
        {
            Numbers = [0, 0, 0, 0, 0, 0];
            InfoMessage = "";
            Solutions.Clear();
        }

        private void Random()
        {
            Random random = new();

            Numbers = SmallNumbers.Concat(IsScary ? BigScaryNumbers : BigNumbers).OrderBy(_ => random.Next()).Take(6).ToArray();
            Total = random.Next(100, 999);
        }

        private void Random6()
        {
            Random random = new();

            Numbers = SmallNumbers.OrderBy(_ => random.Next()).Take(6).ToArray();
            Total = random.Next(100, 999);
        }

        private void Random51()
        {
            Random random = new();

            Numbers = SmallNumbers.OrderBy(_ => random.Next()).Take(5).Concat((IsScary ? BigScaryNumbers : BigNumbers).OrderBy(_ => random.Next()).Take(1)).ToArray();
            Total = random.Next(100, 999);
        }

        private void Random42()
        {
            Random random = new();

            Numbers = SmallNumbers.OrderBy(_ => random.Next()).Take(4).Concat((IsScary ? BigScaryNumbers : BigNumbers).OrderBy(_ => random.Next()).Take(2)).ToArray();
            Total = random.Next(100, 999);
        }

        private void Random33()
        {
            Random random = new();

            Numbers = SmallNumbers.OrderBy(_ => random.Next()).Take(3).Concat((IsScary ? BigScaryNumbers : BigNumbers).OrderBy(_ => random.Next()).Take(3)).ToArray();
            Total = random.Next(100, 999);
        }

        private void Random24()
        {
            Random random = new();

            Numbers = SmallNumbers.OrderBy(_ => random.Next()).Take(2).Concat((IsScary ? BigScaryNumbers : BigNumbers).OrderBy(_ => random.Next()).Take(4)).ToArray();
            Total = random.Next(100, 999);
        }

        private async Task Solve()
        {
            InfoMessage = "";
            Solutions.Clear();
            Running = true;
            ActiveTab = Total;

            StateHasChanged();

            await Task.Yield();

            if (Total < 100 || Total > 999)
            {
                Running = false;
                InfoMessage = "Invalid total, expecting between 100 and 999";
                return;
            }

            if (Numbers.Except(IsScary ? ValidScaryNumbers : ValidNumbers).Any())
            {
                Running = false;
                InfoMessage = "Invalid number found";
                return;
            }

            if (Numbers.Where(x => x <= 10).GroupBy(x => x).Where(x => x.Count() > 2).Any())
            {
                Running = false;
                InfoMessage = "Invalid numbers, expecting a maximum of 2 small numbers";
                return;
            }

            if (Numbers.Where(x => x > 10).GroupBy(x => x).Where(x => x.Count() > 1).Any())
            {
                Running = false;
                InfoMessage = "Invalid numbers, expecting a maximum of 1 big number";
                return;
            }

            if (Numbers.Aggregate(1, (total, x) => total * x) < Total)
            {
                Running = false;
                InfoMessage = "No solution possible, product of numbers is less than total";
                return;
            }

            long TickStart = DateTime.UtcNow.Ticks;

            CancellationTokenSource tokenTimeout = new CancellationTokenSource(TimeSpan.FromSeconds(30));
            CancellationToken token = tokenTimeout.Token;

            for (int i = -10; i < 11; i++)
            {
                Solutions.Add(Total + i, new HashSet<MarkupString>());
            }

            StateHasChanged();

            int[] numbers = Numbers;
            char[] operators = new[] { '+', '-', '*', '/', '_', '?' };
            long iterations = 0;

            Dictionary<int, List<string>> results = new();
            Node bestResult = null;
            int bestValueSums = int.MaxValue;

            try
            {
                void RecurseSolveNumbers(Node[] nodes, int searchedIndex, bool[] wasGenerated, int target, int levels, int valueSums)
                {
                    levels--;

                    for (int i = 0; i < nodes.Length - 1; i++)
                    {
                        if ((++iterations & 4095) == 0)
                        {
                            token.ThrowIfCancellationRequested();
                        }

                        var ni = nodes[i];

                        if (ni == null)
                        {
                            continue;
                        }

                        nodes[i] = null;

                        for (int j = i + 1; j < nodes.Length; j++)
                        {
                            if ((++iterations & 4095) == 0)
                            {
                                token.ThrowIfCancellationRequested();
                            }

                            var nj = nodes[j];

                            if (nj == null)
                            {
                                continue;
                            }

                            if (i < searchedIndex && !wasGenerated[i] && !wasGenerated[j])
                            {
                                continue;
                            }

                            foreach (char op in operators)
                            {
                                if ((++iterations & 4095) == 0)
                                {
                                    token.ThrowIfCancellationRequested();
                                }

                                if (!EvaluateOperation(op, ni.Value, nj.Value, out int r))
                                {
                                    continue;
                                }

                                int opCost = Math.Abs(r);

                                while (opCost % 10 == 0 && opCost != 0)
                                {
                                    opCost /= 10;
                                }

                                if ((ni.Value == 10 || nj.Value == 10) && op == '*')
                                {
                                    opCost = 1;
                                }

                                int newValueSums = valueSums + opCost;

                                if (bestResult == null ||
                                    Math.Abs(r - target) < Math.Abs(bestResult.Value - target) ||
                                    (Math.Abs(r - target) == Math.Abs(bestResult.Value - target) && newValueSums < bestValueSums))
                                {
                                    bestResult = new Node
                                    {
                                        Value = r,
                                        Operation = op,
                                        Left = ni,
                                        Right = nj
                                    };

                                    bestValueSums = newValueSums;
                                }

                                var generated = new Node
                                {
                                    Value = r,
                                    Operation = op,
                                    Left = ni,
                                    Right = nj
                                };

                                nodes[j] = generated;

                                bool oldWasGenerated = wasGenerated[j];
                                wasGenerated[j] = true;

                                if (levels == 0)
                                {
                                    if (Math.Abs(r - target) <= 10)
                                    {
                                        string expression = Format(generated);

                                        Solutions[r].Add(BuildSVG(r, expression));
                                    }
                                }
                                else if (bestResult.Value != target || newValueSums < bestValueSums)
                                {
                                    RecurseSolveNumbers(nodes, i + 1, wasGenerated, target, levels, newValueSums);
                                }

                                wasGenerated[j] = oldWasGenerated;
                                nodes[j] = nj;
                            }
                        }

                        nodes[i] = ni;
                    }
                }

                bool EvaluateOperation(char op, int left, int right, out int result)
                {
                    switch (op)
                    {
                        case '+':
                            {
                                result = left + right;
                                return true;
                            }
                        case '-':
                            {
                                if (left > right)
                                {
                                    result = left - right;
                                    return true;
                                }

                                break;
                            }
                        case '_':
                            {
                                if (right > left)
                                {
                                    result = right - left;
                                    return true;
                                }

                                break;
                            }
                        case '*':
                            {
                                if (left != 1 && right != 1)
                                {
                                    result = left * right;
                                    return true;
                                }

                                break;
                            }
                        case '/':
                            {
                                if (right != 0 && right != 1 && left % right == 0)
                                {
                                    result = left / right;
                                    return true;
                                }

                                break;
                            }
                        case '?':
                            {
                                if (left != 0 && left != 1 && right % left == 0)
                                {
                                    result = right / left;
                                    return true;
                                }

                                break;
                            }
                    }

                    result = 0;
                    return false;
                }

                string Format(Node node)
                {
                    if (node.Left == null && node.Right == null)
                    {
                        return node.Value.ToString();
                    }

                    if (node.Operation == '_')
                    {
                        return $"({Format(node.Right)} - {Format(node.Left)})";
                    }

                    if (node.Operation == '?')
                    {
                        return $"({Format(node.Right)} / {Format(node.Left)})";
                    }

                    if (node.Operation == '*')
                    {
                        return $"({Format(node.Left)} × {Format(node.Right)})";
                    }

                    return $"({Format(node.Left)} {node.Operation} {Format(node.Right)})";
                }

                Node[] nodes = numbers.Select(x => new Node
                {
                    Value = x
                }).ToArray();

                bool[] wasGenerated = new bool[nodes.Length];

                RecurseSolveNumbers(nodes, 0, wasGenerated, Total, nodes.Length - 1, 0);
            }
            catch (Exception ex)
            {
                if (Solutions.All(x => x.Value.Count == 0))
                {
                    InfoMessage = $"Operation timed out. No solutions found.";
                    Running = false;
                    return;
                }
            }

            long TickEnd = DateTime.UtcNow.Ticks;

            ActiveTab = Total;

            foreach (int key in Solutions.Where(x => x.Value.Count == 0).Select(x => x.Key).ToList())
            {
                Solutions.Remove(key);
            }

            if (Solutions.ContainsKey(Total))
            {
                InfoMessage = $"Completed in {new TimeSpan(TickEnd - TickStart).TotalSeconds}s, solved.";
            }
            else if (Solutions.Where(x => x.Key != Total).Any())
            {
                int i = 1;

                while (i <= 11)
                {
                    if (Solutions.ContainsKey(Total + i) && Solutions.ContainsKey(Total - i))
                    {
                        InfoMessage = $"Completed in {new TimeSpan(TickEnd - TickStart).TotalSeconds}s, Closest solution is {i} away at {Total - i} & {Total + 1}.";
                        ActiveTab = Total + i;
                        break;
                    }
                    else if (Solutions.ContainsKey(Total + i))
                    {
                        InfoMessage = $"Completed in {new TimeSpan(TickEnd - TickStart).TotalSeconds}s, Closest solution is {i} away at {Total + i}.";
                        ActiveTab = Total + i;
                        break;
                    }
                    else if (Solutions.ContainsKey(Total - i))
                    {
                        InfoMessage = $"Completed in {new TimeSpan(TickEnd - TickStart).TotalSeconds}s, Closest solution is {i} away at {Total - i}.";
                        ActiveTab = Total - i;
                        break;
                    }

                    i++;
                }

                if (i == 11)
                {
                    if (string.IsNullOrWhiteSpace(InfoMessage))
                    {
                        InfoMessage = $"Completed in {new TimeSpan(TickEnd - TickStart).TotalSeconds}s, No solution within 10 found";
                    }
                }
            }
            else
            {
                if (string.IsNullOrWhiteSpace(InfoMessage))
                {
                    InfoMessage = $"Completed in {new TimeSpan(TickEnd - TickStart).TotalSeconds}s, No solution found";
                }
            }

            Running = false;
        }

        private MarkupString BuildSVG(int target, string solution)
        {
            string SVGStart = "<div class=\"svg-container\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"500\" height=\"40\" viewBox=\"0 0 500 40\"><text x=\"250\" y=\"20\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-family=\"Arial\" font-size=\"24\">";
            string SVGEnd = "</text></svg></div>";
            string text = $"{target} = {solution}";

            return new MarkupString($"{SVGStart}{text}{SVGEnd}");
        }
        
        class Node
        {
            public int Value { get; set; }
            public char Operation { get; set; }
            public Node Left { get; set; }
            public Node Right { get; set; }
        }
    }
}